print("hello\"world\" world")
print('I\'m Piyush chaudhary')
print ("line A")
print("line B")
print("line A\n line B\n line    C")
print("name\tPiyush chaudhary")
print("this is backlash\\")
print ("this is double backlsh\\\\")
print("this is hell\blo")